- name: install zabbix agent
  hosts: all
  gather_facts: no
  become: yes

  tasks:
     - name: install zabbix agent
       shell: |
         CODENAME=`cat /etc/os-release | grep VERSION_CODENAME | awk -F '=' '{ print $2}'` #-F is delimiter
         wget https://repo.zabbix.com/zabbix/5.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_5.0-1%2B${CODENAME}_all.deb
         sudo dpkg -i zabbix-release_5.0-1+${CODENAME}_all.deb
         sudo apt update
         sudo apt install zabbix-agent
         sudo sed -i 's/Server=127.0.0.1/Server=172.14.0.13/g' /etc/zabbix/zabbix_agentd.conf
         sudo sed -i 's/ServerActive=127.0.0.1/ServerActive=172.14.0.13/g' /etc/zabbix/zabbix_agentd.conf
         sudo systemctl restart zabbix-agent
         sudo systemctl enable zabbix-agent
